# crie um programa que leia um número inteiro e mostre a sua tabuada
n1 = int(input('Digite um número: '))
print('***A TABUADA DE {}:***'.format(n1))
print('=' * 15)
print(n1, 'x 1', ' = ', n1*1)
print(n1, 'x 2', ' = ', n1*2)
print(n1, 'x 3', ' = ', n1*3)
print(n1, 'x 4', ' = ', n1*4)
print(n1, 'x 5', ' = ', n1*5)
print(n1, 'x 6', ' = ', n1*6)
print(n1, 'x 7', ' = ', n1*7)
print(n1, 'x 8', ' = ', n1*8)
print(n1, 'x 9', ' = ', n1*9)
print(n1, 'x 10', ' = ', n1*10)
print('=' * 15)